apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: 743506457271.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          value: "mysql"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: MY_NAME
          value: "Sanjan Joshua"
        - name: BACKGROUND_IMAGE_URL
          value: "https://your-s3-bucket.s3.amazonaws.com/bg.jpg"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: 743506457271.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          value: "mysql"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: MY_NAME
          value: "Sanjan Joshua"
        - name: BACKGROUND_IMAGE_URL
          value: "https://your-s3-bucket.s3.amazonaws.com/bg.jpg"

